# Site Settings
title: "Will Presley, Web Developer"
email: me@willpresley.com
meta-description: "The personal site of Will Presley, professional web developer, soccer player/fan, and hobbyist Android developer. Based in Athens, Ohio."
description: "The personal site of Will Presley, professional web developer, soccer player/fan, and hobbyist Android developer. Based in Athens, Ohio."
location: "Athens, Ohio"
baseurl: ""
url: "https://willpresley.com"
author:
  name: "Will Presley"
  url: "https://willpresley.com"
  avatar: "https://gravatar.com/avatar/038f89bfe8b9a129453531a4235f8eea?size=512"

# RSS Feed Settings
name: "WillPresley.com"

# Build Settings
source: /home/will/jekyll
# destination: <HIDDEN IN BUILD SCRIPT>
encoding: UTF-8
exclude: [config.rb, README.md]
keep_files: [google1482399d71dc90a7.html]
timezone: America/New_York

# Content Settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: /blog/:title/
lsi: true

collections:
  projects:
    refname: proj
    output: true

plugins:
  - jekyll-target-blank
  - jekyll-inline-svg

# Sitemap Settings
sitemap:
  exclude:
    - "/feed.xml"
  include_posts:
    - "/index.html"
    - "/blog.md"

svg:
  optimize: true
