# Site Settings
title: "Will Presley, Web Developer"
email: william.presley.jr@gmail.com
meta-description: "The personal site of Will Presley, professional web developer, soccer player/fan, and hobbyist Android developer. Based in Athens, Ohio."
description: "The personal site of Will Presley, professional web developer, soccer player/fan, and hobbyist Android developer. Based in Athens, Ohio."
location: "Athens, Ohio"
baseurl: ""
url: "http://willpresley.com"

# RSS Feed Settings
name: "WillPresley.com"

# Build Settings
source: /home/will/jekyll
# destination: <HIDDEN IN BUILD SCRIPT>
encoding: UTF-8
exclude: [config.rb, README.md]
keep_files: [admin]
timezone: America/New_York

# Content Settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /blog/:title/
lsi: true

collections:
  projects:
    refname: proj
    output: true

# Sitemap Settings
sitemap:
  exclude:
    - "/feed.xml"
  include_posts:
    - "/index.html"
    - "/blog.md"
