# Site Settings
title: "Will Presley, Web Developer"
email: william.presley.jr@gmail.com
meta-description: "The personal site of Will Presley, professional web developer, soccer player/fan, and hobbyist Android developer. Based in Athens, Ohio."
location: "Athens, Ohio"
baseurl: ""
url: "http://willpresley.com"

#Build Settings
source: /home/will/jekyll
# destination: <HIDDEN IN BUILD SCRIPT>
encoding: UTF-8
exclude: [config.rb, README.md]
keep_files: [admin]
timezone: America/New_York
# markdown: redcarpet
markdown: kramdown
highlighter: pygments
permalink: /:title
lsi: true
